### ISSUE TITLE
Conflicts with other plugins.

### ISSUE THREAD

**Issue by sdbds** [hnmr293/stable-diffusion-webui-dumpunet#2]
both this and [Stable-Diffusion-Webui-Civitai-Helper](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper)

import modules.scripts as scripts
from scripts.lib import XXX

Civitai-Helper Pre-reading, Dumpunet unable to load.

**Comment by hnmr293** [comment]
oh, sorry!
I have fixed. See 4859d2f4109ba98e627bd78242ea781ffe3dae56.
Thank you.
