### ISSUE TITLE
How to save the generated u-net feature image as an image like txt2img?

### ISSUE THREAD

**Issue by jaycecd** [hnmr293/stable-diffusion-webui-dumpunet#5]
I want to save the feature maps, but after checking "Dump feature tensors to files", I get a pair of binary files in .bin format, so if I want to save the feature maps of the web page, I can only save each feature map by right clicking on it, which is too slow. How to automatically save to local like txt2img? Is it possible to allow users to save grid images locally?
![image](https://github.com/hnmr293/stable-diffusion-webui-dumpunet/assets/33342388/c2c89d12-4567-4c9e-9568-3ae84e872635)

**Comment by hnmr293** [comment]
Thank you for your feedback.
I have updated for it.
Now you can see all images in your output directory like this.

![image](https://github.com/hnmr293/stable-diffusion-webui-dumpunet/assets/120772120/146dd360-845c-40db-89e8-5d395eed7c37)

Note 1: how to open the directory.
![image](https://github.com/hnmr293/stable-diffusion-webui-dumpunet/assets/120772120/83b1ce54-81d5-4268-ba4f-74d4188619bb)

Note 2: The option "Dump feature tensors to files" is actually for my own use, and it is not documented, sorry. It splits tensors by channels and dumps them in binary form, not image format.

**Comment by jaycecd** [comment]
Wow, what a great job as well as a quick response, thank you so much!
But after using it, I have a small suggestion please consider, can the rules for naming images use the same prefix? The current naming rule for image files is:
`{num}-{seed}-dumpunet-{layer name}-{step}`,
But there's a problem: I can't tell at a glance which dumpunet files belong to the same generation based on the file names, so is it possible to set the `num` prefix to be the same as the natively generated images? 
That is, fix `num` and `seed` instead of increasing `num` sequentially, so that I can see at a glance which dumpunet files belong to the same generation based on the filename, and the difference of `{layer name}-{step}` after it will not cause the files to be overwritten.
Thanks again for the quick response!

**Comment by hnmr293** [comment]
OK, it sounds good. I have updated.
Now saved images have same number as original one.

Note:
I added new option for image saving. Please check button in `Setting` tab.

![image](https://github.com/hnmr293/stable-diffusion-webui-dumpunet/assets/120772120/0743aa76-7d88-4e0d-b8e6-aa3e5b7c22aa)

**Comment by jaycecd** [comment]
Wow, thanks a lot, currently dumpunet is saving the image properly with the filename I mentioned, thanks for your hard work!
